/* eslint-disable no-unused-vars */
import { Meteor } from 'meteor/meteor';
import SimpleSchema from 'simpl-schema';
import { check } from 'meteor/check';
import { _ } from 'meteor/underscore';
import { Roles } from 'meteor/alanning:roles';
import BaseCollection from '../base/BaseCollection';
import { ROLE } from '../role/Role';

export const AuditedBalanceSheetPublications = {
  AuditedBalanceSheet: 'AuditedBalanceSheet',
  AuditedBalanceSheetAdmin: 'AuditedBalanceSheetAdmin',
};

class AuditedBalanceSheetCollection extends BaseCollection {
  constructor() {
    super('AuditedBalanceSheets', new SimpleSchema({
      owner: String,
      Petty_cash_year6: Number,
      Petty_cash_year7: Number,
      Petty_cash_year8: Number,
      Petty_cash_year9: Number,

      Cash_year6: Number,
      Cash_year7: Number,
      Cash_year8: Number,
      Cash_year9: Number,

      Cash_in_banksDraw_on_Line_of_Credit_year6: Number,
      Cash_in_banksDraw_on_Line_of_Credit_year7: Number,
      Cash_in_banksDraw_on_Line_of_Credit_year8: Number,
      Cash_in_banksDraw_on_Line_of_Credit_year9: Number,

      Total_Cash_and_Cash_Equivalents_year6: Number,
      Total_Cash_and_Cash_Equivalents_year7: Number,
      Total_Cash_and_Cash_Equivalents_year8: Number,
      Total_Cash_and_Cash_Equivalents_year9: Number,

      Accounts_receivable_year6: Number,
      Accounts_receivable_year7: Number,
      Accounts_receivable_year8: Number,
      Accounts_receivable_year9: Number,

      Due_from_other_fund_year6: Number,
      Due_from_other_fund_year7: Number,
      Due_from_other_fund_year8: Number,
      Due_from_other_fund_year9: Number,

      Interest_and_dividends_receivable_year6: Number,
      Interest_and_dividends_receivable_year7: Number,
      Interest_and_dividends_receivable_year8: Number,
      Interest_and_dividends_receivable_year9: Number,

      Inventory_prepaid_items_and_other_assets_year6: Number,
      Inventory_prepaid_items_and_other_assets_year7: Number,
      Inventory_prepaid_items_and_other_assets_year8: Number,
      Inventory_prepaid_items_and_other_assets_year9: Number,

      Notes_receivable_due_within_one_year_year6: Number,
      Notes_receivable_due_within_one_year_year7: Number,
      Notes_receivable_due_within_one_year_year8: Number,
      Notes_receivable_due_within_one_year_year9: Number,

      Notes_receivable_due_after_one_year_year6: Number,
      Notes_receivable_due_after_one_year_year7: Number,
      Notes_receivable_due_after_one_year_year8: Number,
      Notes_receivable_due_after_one_year_year9: Number,

      Security_Deposits_year6: Number,
      Security_Deposits_year7: Number,
      Security_Deposits_year8: Number,
      Security_Deposits_year9: Number,

      Cash_held_by_investment_manager_year6: Number,
      Cash_held_by_investment_manager_year7: Number,
      Cash_held_by_investment_manager_year8: Number,
      Cash_held_by_investment_manager_year9: Number,

      Mutual_Funds_year6: Number,
      Mutual_Funds_year7: Number,
      Mutual_Funds_year8: Number,
      Mutual_Funds_year9: Number,

      Commingled_funds_year6: Number,
      Commingled_funds_year7: Number,
      Commingled_funds_year8: Number,
      Commingled_funds_year9: Number,

      Hedge_funds_year6: Number,
      Hedge_funds_year7: Number,
      Hedge_funds_year8: Number,
      Hedge_funds_year9: Number,

      Private_equity_year6: Number,
      Private_equity_year7: Number,
      Private_equity_year8: Number,
      Private_equity_year9: Number,

      Common_trust_fund_year6: Number,
      Common_trust_fund_year7: Number,
      Common_trust_fund_year8: Number,
      Common_trust_fund_year9: Number,

      Common_preferred_stock_year6: Number,
      Common_preferred_stock_year7: Number,
      Common_preferred_stock_year8: Number,
      Common_preferred_stock_year9: Number,

      Private_debt_year6: Number,
      Private_debt_year7: Number,
      Private_debt_year8: Number,
      Private_debt_year9: Number,

      Other_year6: Number,
      Other_year7: Number,
      Other_year8: Number,
      Other_year9: Number,

      Subtotal_Investment_year6: Number,
      Subtotal_Investment_year7: Number,
      Subtotal_Investment_year8: Number,
      Subtotal_Investment_year9: Number,

      US_treasuries_year6: Number,
      US_treasuries_year7: Number,
      US_treasuries_year8: Number,
      US_treasuries_year9: Number,

      US_agencies_year6: Number,
      US_agencies_year7: Number,
      US_agencies_year8: Number,
      US_agencies_year9: Number,

      Subtotal_Loan_Fund_year6: Number,
      Subtotal_Loan_Fund_year7: Number,
      Subtotal_Loan_Fund_year8: Number,
      Subtotal_Loan_Fund_year9: Number,

      Buildings_year6: Number,
      Buildings_year7: Number,
      Buildings_year8: Number,
      Buildings_year9: Number,

      Leasehold_improvements_year6: Number,
      Leasehold_improvements_year7: Number,
      Leasehold_improvements_year8: Number,
      Leasehold_improvements_year9: Number,

      Furniture_fixtures_and_equipment_year6: Number,
      Furniture_fixtures_and_equipment_year7: Number,
      Furniture_fixtures_and_equipment_year8: Number,
      Furniture_fixtures_and_equipment_year9: Number,

      Less_accumulated_depreciation_year6: Number,
      Less_accumulated_depreciation_year7: Number,
      Less_accumulated_depreciation_year8: Number,
      Less_accumulated_depreciation_year9: Number,

      Net_year6: Number,
      Net_year7: Number,
      Net_year8: Number,
      Net_year9: Number,

      Land_A_year6: Number,
      Land_A_year7: Number,
      Land_A_year8: Number,
      Land_A_year9: Number,

      Land_B_year6: Number,
      Land_B_year7: Number,
      Land_B_year8: Number,
      Land_B_year9: Number,

      Construction_in_Progress_year6: Number,
      Construction_in_Progress_year7: Number,
      Construction_in_Progress_year8: Number,
      Construction_in_Progress_year9: Number,

      Subtotal_Capital_Assets_net_year6: Number,
      Subtotal_Capital_Assets_net_year7: Number,
      Subtotal_Capital_Assets_net_year8: Number,
      Subtotal_Capital_Assets_net_year9: Number,

      Restricted_cash_year6: Number,
      Restricted_cash_year7: Number,
      Restricted_cash_year8: Number,
      Restricted_cash_year9: Number,

      Total_Other_Assets_year6: Number,
      Total_Other_Assets_year7: Number,
      Total_Other_Assets_year8: Number,
      Total_Other_Assets_year9: Number,

      Deferred_outflows_of_resources_related_to_pensions_year6: Number,
      Deferred_outflows_of_resources_related_to_pensions_year7: Number,
      Deferred_outflows_of_resources_related_to_pensions_year8: Number,
      Deferred_outflows_of_resources_related_to_pensions_year9: Number,

      Deferred_outflows_of_resources_related_to_OPEB_year6: Number,
      Deferred_outflows_of_resources_related_to_OPEB_year7: Number,
      Deferred_outflows_of_resources_related_to_OPEB_year8: Number,
      Deferred_outflows_of_resources_related_to_OPEB_year9: Number,

      Total_assets_and_deferred_outflows_of_resources_year6: Number,
      Total_assets_and_deferred_outflows_of_resources_year7: Number,
      Total_assets_and_deferred_outflows_of_resources_year8: Number,
      Total_assets_and_deferred_outflows_of_resources_year9: Number,

      Accounts_payable_and_accrued_liabilities_year6: Number,
      Accounts_payable_and_accrued_liabilities_year7: Number,
      Accounts_payable_and_accrued_liabilities_year8: Number,
      Accounts_payable_and_accrued_liabilities_year9: Number,

      Due_to_fund_year6: Number,
      Due_to_fund_year7: Number,
      Due_to_fund_year8: Number,
      Due_to_fund_year9: Number,

      Due_to_other_fund_year6: Number,
      Due_to_other_fund_year7: Number,
      Due_to_other_fund_year8: Number,
      Due_to_other_fund_year9: Number,

      Accrued_vacation_year6: Number,
      Accrued_vacation_year7: Number,
      Accrued_vacation_year8: Number,
      Accrued_vacation_year9: Number,

      Workers_compensation_year6: Number,
      Workers_compensation_year7: Number,
      Workers_compensation_year8: Number,
      Workers_compensation_year9: Number,

      Accrued_management_retirement_plan_year6: Number,
      Accrued_management_retirement_plan_year7: Number,
      Accrued_management_retirement_plan_year8: Number,
      Accrued_management_retirement_plan_year9: Number,

      Accrued_lease_guaranty_obligation_year6: Number,
      Accrued_lease_guaranty_obligation_year7: Number,
      Accrued_lease_guaranty_obligation_year8: Number,
      Accrued_lease_guaranty_obligation_year9: Number,

      Capital_lease_obligation_year6: Number,
      Capital_lease_obligation_year7: Number,
      Capital_lease_obligation_year8: Number,
      Capital_lease_obligation_year9: Number,

      Notes_payable_Building_A_acquisition_year6: Number,
      Notes_payable_Building_A_acquisition_year7: Number,
      Notes_payable_Building_A_acquisition_year8: Number,
      Notes_payable_Building_A_acquisition_year9: Number,

      Net_Pension_Liability_year6: Number,
      Net_Pension_Liability_year7: Number,
      Net_Pension_Liability_year8: Number,
      Net_Pension_Liability_year9: Number,

      Net_OPEB_Liability_year6: Number,
      Net_OPEB_Liability_year7: Number,
      Net_OPEB_Liability_year8: Number,
      Net_OPEB_Liability_year9: Number,

      Line_of_Credit_Building_A_year6: Number,
      Line_of_Credit_Building_A_year7: Number,
      Line_of_Credit_Building_A_year8: Number,
      Line_of_Credit_Building_A_year9: Number,

      Line_of_Credit_Building_B_year6: Number,
      Line_of_Credit_Building_B_year7: Number,
      Line_of_Credit_Building_B_year8: Number,
      Line_of_Credit_Building_B_year9: Number,

      Longterm_liabilities_due_within_one_year_year6: Number,
      Longterm_liabilities_due_within_one_year_year7: Number,
      Longterm_liabilities_due_within_one_year_year8: Number,
      Longterm_liabilities_due_within_one_year_year9: Number,

      Total_Liabilities_year6: Number,
      Total_Liabilities_year7: Number,
      Total_Liabilities_year8: Number,
      Total_Liabilities_year9: Number,

      Invested_in_capital_assets_net_of_related_debt_year6: Number,
      Invested_in_capital_assets_net_of_related_debt_year7: Number,
      Invested_in_capital_assets_net_of_related_debt_year8: Number,
      Invested_in_capital_assets_net_of_related_debt_year9: Number,

      Total_net_position_year6: Number,
      Total_net_position_year7: Number,
      Total_net_position_year8: Number,
      Total_net_position_year9: Number,

      Total_Liabilities_Deferred_Inflows_of_Resources_and_Net_Position_year6: Number,
      Total_Liabilities_Deferred_Inflows_of_Resources_and_Net_Position_year7: Number,
      Total_Liabilities_Deferred_Inflows_of_Resources_and_Net_Position_year8: Number,
      Total_Liabilities_Deferred_Inflows_of_Resources_and_Net_Position_year9: Number,
    }));
  }

  /* Defines a new AuditedBalanceSheet item.
    * @param {Object} data - Contains fields for AuditedBalanceSheet.
    * @return {String} docID - The docID of the newly inserted document.
    */
  define({ owner }) {
    const auditedBalanceSheetData = {
      owner,
      Petty_cash_year6: 0,
      Petty_cash_year7: 0,
      Petty_cash_year8: 0,
      Petty_cash_year9: 0,
      Cash_year6: 0,
      Cash_year7: 0,
      Cash_year8: 0,
      Cash_year9: 0,
      Cash_in_banksDraw_on_Line_of_Credit_year6: 0,
      Cash_in_banksDraw_on_Line_of_Credit_year7: 0,
      Cash_in_banksDraw_on_Line_of_Credit_year8: 0,
      Cash_in_banksDraw_on_Line_of_Credit_year9: 0,
      Total_Cash_and_Cash_Equivalents_year6: 0,
      Total_Cash_and_Cash_Equivalents_year7: 0,
      Total_Cash_and_Cash_Equivalents_year8: 0,
      Total_Cash_and_Cash_Equivalents_year9: 0,
      Accounts_receivable_year6: 0,
      Accounts_receivable_year7: 0,
      Accounts_receivable_year8: 0,
      Accounts_receivable_year9: 0,
      Due_from_other_fund_year6: 0,
      Due_from_other_fund_year7: 0,
      Due_from_other_fund_year8: 0,
      Due_from_other_fund_year9: 0,
      Interest_and_dividends_receivable_year6: 0,
      Interest_and_dividends_receivable_year7: 0,
      Interest_and_dividends_receivable_year8: 0,
      Interest_and_dividends_receivable_year9: 0,
      Inventory_prepaid_items_and_other_assets_year6: 0,
      Inventory_prepaid_items_and_other_assets_year7: 0,
      Inventory_prepaid_items_and_other_assets_year8: 0,
      Inventory_prepaid_items_and_other_assets_year9: 0,
      Notes_receivable_due_within_one_year_year6: 0,
      Notes_receivable_due_within_one_year_year7: 0,
      Notes_receivable_due_within_one_year_year8: 0,
      Notes_receivable_due_within_one_year_year9: 0,
      Notes_receivable_due_after_one_year_year6: 0,
      Notes_receivable_due_after_one_year_year7: 0,
      Notes_receivable_due_after_one_year_year8: 0,
      Notes_receivable_due_after_one_year_year9: 0,
      Security_Deposits_year6: 0,
      Security_Deposits_year7: 0,
      Security_Deposits_year8: 0,
      Security_Deposits_year9: 0,
      Cash_held_by_investment_manager_year6: 0,
      Cash_held_by_investment_manager_year7: 0,
      Cash_held_by_investment_manager_year8: 0,
      Cash_held_by_investment_manager_year9: 0,
      Mutual_Funds_year6: 0,
      Mutual_Funds_year7: 0,
      Mutual_Funds_year8: 0,
      Mutual_Funds_year9: 0,
      Commingled_funds_year6: 0,
      Commingled_funds_year7: 0,
      Commingled_funds_year8: 0,
      Commingled_funds_year9: 0,
      Hedge_funds_year6: 0,
      Hedge_funds_year7: 0,
      Hedge_funds_year8: 0,
      Hedge_funds_year9: 0,
      Private_equity_year6: 0,
      Private_equity_year7: 0,
      Private_equity_year8: 0,
      Private_equity_year9: 0,
      Common_trust_fund_year6: 0,
      Common_trust_fund_year7: 0,
      Common_trust_fund_year8: 0,
      Common_trust_fund_year9: 0,
      Common_preferred_stock_year6: 0,
      Common_preferred_stock_year7: 0,
      Common_preferred_stock_year8: 0,
      Common_preferred_stock_year9: 0,
      Private_debt_year6: 0,
      Private_debt_year7: 0,
      Private_debt_year8: 0,
      Private_debt_year9: 0,
      Other_year6: 0,
      Other_year7: 0,
      Other_year8: 0,
      Other_year9: 0,
      Subtotal_Investment_year6: 0,
      Subtotal_Investment_year7: 0,
      Subtotal_Investment_year8: 0,
      Subtotal_Investment_year9: 0,
      US_treasuries_year6: 0,
      US_treasuries_year7: 0,
      US_treasuries_year8: 0,
      US_treasuries_year9: 0,
      US_agencies_year6: 0,
      US_agencies_year7: 0,
      US_agencies_year8: 0,
      US_agencies_year9: 0,
      Subtotal_Loan_Fund_year6: 0,
      Subtotal_Loan_Fund_year7: 0,
      Subtotal_Loan_Fund_year8: 0,
      Subtotal_Loan_Fund_year9: 0,
      Investments_year6: 0,
      Investments_year7: 0,
      Investments_year8: 0,
      Investments_year9: 0,
      Buildings_year6: 0,
      Buildings_year7: 0,
      Buildings_year8: 0,
      Buildings_year9: 0,
      Leasehold_improvements_year6: 0,
      Leasehold_improvements_year7: 0,
      Leasehold_improvements_year8: 0,
      Leasehold_improvements_year9: 0,
      Furniture_fixtures_and_equipment_year6: 0,
      Furniture_fixtures_and_equipment_year7: 0,
      Furniture_fixtures_and_equipment_year8: 0,
      Furniture_fixtures_and_equipment_year9: 0,
      Less_accumulated_depreciation_year6: 0,
      Less_accumulated_depreciation_year7: 0,
      Less_accumulated_depreciation_year8: 0,
      Less_accumulated_depreciation_year9: 0,
      Net_year6: 0,
      Net_year7: 0,
      Net_year8: 0,
      Net_year9: 0,
      Land_A_year6: 0,
      Land_A_year7: 0,
      Land_A_year8: 0,
      Land_A_year9: 0,
      Land_B_year6: 0,
      Land_B_year7: 0,
      Land_B_year8: 0,
      Land_B_year9: 0,
      Construction_in_Progress_year6: 0,
      Construction_in_Progress_year7: 0,
      Construction_in_Progress_year8: 0,
      Construction_in_Progress_year9: 0,
      Subtotal_Capital_Assets_net_year6: 0,
      Subtotal_Capital_Assets_net_year7: 0,
      Subtotal_Capital_Assets_net_year8: 0,
      Subtotal_Capital_Assets_net_year9: 0,
      Investments_Buildings_year6: 0,
      Investments_Buildings_year7: 0,
      Investments_Buildings_year8: 0,
      Investments_Buildings_year9: 0,
      Investments_Leasehold_improvements_year6: 0,
      Investments_Leasehold_improvements_year7: 0,
      Investments_Leasehold_improvements_year8: 0,
      Investments_Leasehold_improvements_year9: 0,
      Investments_Furniture_year6: 0,
      Investments_Furniture_year7: 0,
      Investments_Furniture_year8: 0,
      Investments_Furniture_year9: 0,
      Investments_fixtures_and_equipment_year6: 0,
      Investments_fixtures_and_equipment_year7: 0,
      Investments_fixtures_and_equipment_year8: 0,
      Investments_fixtures_and_equipment_year9: 0,
      Vehicles_year6: 0,
      Vehicles_year7: 0,
      Vehicles_year8: 0,
      Vehicles_year9: 0,
      Investments_Less_accumulated_depreciation_year6: 0,
      Investments_Less_accumulated_depreciation_year7: 0,
      Investments_Less_accumulated_depreciation_year8: 0,
      Investments_Less_accumulated_depreciation_year9: 0,
      Investments_Net_year6: 0,
      Investments_Net_year7: 0,
      Investments_Net_year8: 0,
      Investments_Net_year9: 0,
      Land_year6: 0,
      Land_year7: 0,
      Land_year8: 0,
      Land_year9: 0,
      Subtotal_Limited_Liability_Company_Bs_assets_net_year6: 0,
      Subtotal_Limited_Liability_Company_Bs_assets_net_year7: 0,
      Subtotal_Limited_Liability_Company_Bs_assets_net_year8: 0,
      Subtotal_Limited_Liability_Company_Bs_assets_net_year9: 0,
      Capital_Assets_net_year6: 0,
      Capital_Assets_net_year7: 0,
      Capital_Assets_net_year8: 0,
      Capital_Assets_net_year9: 0,
      Restricted_cash_year6: 0,
      Restricted_cash_year7: 0,
      Restricted_cash_year8: 0,
      Restricted_cash_year9: 0,
      Total_Other_Assets_year6: 0,
      Total_Other_Assets_year7: 0,
      Total_Other_Assets_year8: 0,
      Total_Other_Assets_year9: 0,
      Deferred_outflows_of_resources_related_to_pensions_year6: 0,
      Deferred_outflows_of_resources_related_to_pensions_year7: 0,
      Deferred_outflows_of_resources_related_to_pensions_year8: 0,
      Deferred_outflows_of_resources_related_to_pensions_year9: 0,
      Deferred_outflows_of_resources_related_to_OPEB_year6: 0,
      Deferred_outflows_of_resources_related_to_OPEB_year7: 0,
      Deferred_outflows_of_resources_related_to_OPEB_year8: 0,
      Deferred_outflows_of_resources_related_to_OPEB_year9: 0,
      Total_assets_and_deferred_outflows_of_resources_year6: 0,
      Total_assets_and_deferred_outflows_of_resources_year7: 0,
      Total_assets_and_deferred_outflows_of_resources_year8: 0,
      Total_assets_and_deferred_outflows_of_resources_year9: 0,
      Accounts_payable_and_accrued_liabilities_year6: 0,
      Accounts_payable_and_accrued_liabilities_year7: 0,
      Accounts_payable_and_accrued_liabilities_year8: 0,
      Accounts_payable_and_accrued_liabilities_year9: 0,
      Due_to_fund_year6: 0,
      Due_to_fund_year7: 0,
      Due_to_fund_year8: 0,
      Due_to_fund_year9: 0,
      Due_to_other_fund_year6: 0,
      Due_to_other_fund_year7: 0,
      Due_to_other_fund_year8: 0,
      Due_to_other_fund_year9: 0,
      Accrued_vacation_year6: 0,
      Accrued_vacation_year7: 0,
      Accrued_vacation_year8: 0,
      Accrued_vacation_year9: 0,
      Workers_compensation_year6: 0,
      Workers_compensation_year7: 0,
      Workers_compensation_year8: 0,
      Workers_compensation_year9: 0,
      Accrued_management_retirement_plan_year6: 0,
      Accrued_management_retirement_plan_year7: 0,
      Accrued_management_retirement_plan_year8: 0,
      Accrued_management_retirement_plan_year9: 0,
      Accrued_lease_guaranty_obligation_year6: 0,
      Accrued_lease_guaranty_obligation_year7: 0,
      Accrued_lease_guaranty_obligation_year8: 0,
      Accrued_lease_guaranty_obligation_year9: 0,
      Capital_lease_obligation_year6: 0,
      Capital_lease_obligation_year7: 0,
      Capital_lease_obligation_year8: 0,
      Capital_lease_obligation_year9: 0,
      Notes_payable_Building_A_acquisition_year6: 0,
      Notes_payable_Building_A_acquisition_year7: 0,
      Notes_payable_Building_A_acquisition_year8: 0,
      Notes_payable_Building_A_acquisition_year9: 0,
      Net_Pension_Liability_year6: 0,
      Net_Pension_Liability_year7: 0,
      Net_Pension_Liability_year8: 0,
      Net_Pension_Liability_year9: 0,
      Net_OPEB_Liability_year6: 0,
      Net_OPEB_Liability_year7: 0,
      Net_OPEB_Liability_year8: 0,
      Net_OPEB_Liability_year9: 0,
      Line_of_Credit_Building_A_year6: 0,
      Line_of_Credit_Building_A_year7: 0,
      Line_of_Credit_Building_A_year8: 0,
      Line_of_Credit_Building_A_year9: 0,
      Line_of_Credit_Building_B_year6: 0,
      Line_of_Credit_Building_B_year7: 0,
      Line_of_Credit_Building_B_year8: 0,
      Line_of_Credit_Building_B_year9: 0,
      Debt_service_year6: 0,
      Debt_service_year7: 0,
      Debt_service_year8: 0,
      Debt_service_year9: 0,
      Longterm_liabilities_due_within_one_year_year6: 0,
      Longterm_liabilities_due_within_one_year_year7: 0,
      Longterm_liabilities_due_within_one_year_year8: 0,
      Longterm_liabilities_due_within_one_year_year9: 0,
      Long_term_Accrued_vacation_year6: 0,
      Long_term_Accrued_vacation_year7: 0,
      Long_term_Accrued_vacation_year8: 0,
      Long_term_Accrued_vacation_year9: 0,
      Long_term_Workers_compensation_year6: 0,
      Long_term_Workers_compensation_year7: 0,
      Long_term_Workers_compensation_year8: 0,
      Long_term_Workers_compensation_year9: 0,
      Long_term_Accrued_management_retirement_plan_year6: 0,
      Long_term_Accrued_management_retirement_plan_year7: 0,
      Long_term_Accrued_management_retirement_plan_year8: 0,
      Long_term_Accrued_management_retirement_plan_year9: 0,
      Long_term_Accrued_lease_guaranty_obligation_year6: 0,
      Long_term_Accrued_lease_guaranty_obligation_year7: 0,
      Long_term_Accrued_lease_guaranty_obligation_year8: 0,
      Long_term_Accrued_lease_guaranty_obligation_year9: 0,
      Long_term_Capital_lease_obligation_year6: 0,
      Long_term_Capital_lease_obligation_year7: 0,
      Long_term_Capital_lease_obligation_year8: 0,
      Long_term_Capital_lease_obligation_year9: 0,
      Long_term_Notes_payable_Building_A_acquisition_year6: 0,
      Long_term_Notes_payable_Building_A_acquisition_year7: 0,
      Long_term_Notes_payable_Building_A_acquisition_year8: 0,
      Long_term_Notes_payable_Building_A_acquisition_year9: 0,
      Long_term_Net_Pension_Liability_year6: 0,
      Long_term_Net_Pension_Liability_year7: 0,
      Long_term_Net_Pension_Liability_year8: 0,
      Long_term_Net_Pension_Liability_year9: 0,
      Long_term_Net_OPEB_Liability_year6: 0,
      Long_term_Net_OPEB_Liability_year7: 0,
      Long_term_Net_OPEB_Liability_year8: 0,
      Long_term_Net_OPEB_Liability_year9: 0,
      Long_term_Line_of_Credit_Building_A_year6: 0,
      Long_term_Line_of_Credit_Building_A_year7: 0,
      Long_term_Line_of_Credit_Building_A_year8: 0,
      Long_term_Line_of_Credit_Building_A_year9: 0,
      Long_term_Line_of_Credit_Building_B_year6: 0,
      Long_term_Line_of_Credit_Building_B_year7: 0,
      Long_term_Line_of_Credit_Building_B_year8: 0,
      Long_term_Line_of_Credit_Building_B_year9: 0,
      Long_term_Debt_service_year6: 0,
      Long_term_Debt_service_year7: 0,
      Long_term_Debt_service_year8: 0,
      Long_term_Debt_service_year9: 0,
      Longterm_liabilities_due_after_one_year_year6: 0,
      Longterm_liabilities_due_after_one_year_year7: 0,
      Longterm_liabilities_due_after_one_year_year8: 0,
      Longterm_liabilities_due_after_one_year_year9: 0,
      Total_Liabilities_year6: 0,
      Total_Liabilities_year7: 0,
      Total_Liabilities_year8: 0,
      Total_Liabilities_year9: 0,
      Deferred_inflows_of_resources_related_to_pensions_year6: 0,
      Deferred_inflows_of_resources_related_to_pensions_year7: 0,
      Deferred_inflows_of_resources_related_to_pensions_year8: 0,
      Deferred_inflows_of_resources_related_to_pensions_year9: 0,
      Deferred_inflows_of_resources_related_to_OPEB_year6: 0,
      Deferred_inflows_of_resources_related_to_OPEB_year7: 0,
      Deferred_inflows_of_resources_related_to_OPEB_year8: 0,
      Deferred_inflows_of_resources_related_to_OPEB_year9: 0,
      Total_liabilities_and_deferred_inflows_of_resources_year6: 0,
      Total_liabilities_and_deferred_inflows_of_resources_year7: 0,
      Total_liabilities_and_deferred_inflows_of_resources_year8: 0,
      Total_liabilities_and_deferred_inflows_of_resources_year9: 0,
      Invested_in_capital_assets_net_of_related_debt_year6: 0,
      Invested_in_capital_assets_net_of_related_debt_year7: 0,
      Invested_in_capital_assets_net_of_related_debt_year8: 0,
      Invested_in_capital_assets_net_of_related_debt_year9: 0,
      Restricted_federal_funds_year6: 0,
      Restricted_federal_funds_year7: 0,
      Restricted_federal_funds_year8: 0,
      Restricted_federal_funds_year9: 0,
      Unrestricted_year6: 0,
      Unrestricted_year7: 0,
      Unrestricted_year8: 0,
      Unrestricted_year9: 0,
      Total_net_position_year6: 0,
      Total_net_position_year7: 0,
      Total_net_position_year8: 0,
      Total_net_position_year9: 0,
      Total_Liabilities_Deferred_Inflows_of_Resources_and_Net_Position_year6: 0,
      Total_Liabilities_Deferred_Inflows_of_Resources_and_Net_Position_year7: 0,
      Total_Liabilities_Deferred_Inflows_of_Resources_and_Net_Position_year8: 0,
      Total_Liabilities_Deferred_Inflows_of_Resources_and_Net_Position_year9: 0,
    };

    const docID = this._collection.insert(auditedBalanceSheetData);
    return docID;
  }

  /**
    * Updates the given document with new field values.
    * @param {String} docID - The ID of the document to update.
    * @param {Object} updatedFields - The new values for the fields.
    */
  update(docID, updatedFields) {
    const updateData = {};
    Object.entries(updatedFields).forEach(([key, value]) => {
      if (_.isNumber(value)) {
        updateData[key] = value;
      }
    });
    this._collection.update(docID, { $set: updateData });
  }

  /**
    * A stricter form of remove that throws an error if the document or docID could not be found.
    * @param {String | Object} name - A document or docID in this collection.
    * @return {Boolean} true
    */
  removeIt(name) {
    const doc = this.findDoc(name);
    check(doc, Object);
    this._collection.remove(doc._id);
    return true;
  }

  /**
    * Default publication method for entities.
    * It publishes the entire collection for admin and just the AuditedBalanceSheet associated to an owner.
    */
  publish() {
    if (Meteor.isServer) {
      const instance = this;

      // Publish only documents associated with the logged-in user
      Meteor.publish(AuditedBalanceSheetPublications.AuditedBalanceSheet, function publish() {
        if (this.userId) {
          const username = Meteor.users.findOne(this.userId).username;
          return instance._collection.find({ owner: username });
        }
        return this.ready();
      });

      // Publish all documents, but only for admin users
      Meteor.publish('auditedBalanceSheets', function () {
        return AuditedBalanceSheets.find(); // Ensure it is correctly publishing documents
      });

    }
  }

  /**
    * Subscription method for AuditedBalanceSheet owned by the current user.
    */
  subscribeAuditedBalanceSheet() {
    return Meteor.subscribe('auditedBalanceSheet');
  }

  getCollectionName() {
    return this._collection._name;
  }

  /**
    * Subscription method for admin users.
    * It subscribes to the entire collection.
    */
  subscribeAuditedBalanceSheetAdmin() {
    if (Meteor.isClient) {
      return Meteor.subscribe(AuditedBalanceSheetPublications.AuditedBalanceSheetAdmin);
    }
    return null;
  }

  /**
    * Default implementation of assertValidRoleForMethod. Asserts that userId is logged in as an Admin or User.
    * This is used in the define, update, and removeIt Meteor methods.
    * @param {String} userId - The userId of the logged in user.
    * @throws {Meteor.Error} If the user is not logged in as an Admin or User.
    */
  assertValidRoleForMethod(userId) {
    this.assertRole(userId, [ROLE.ADMIN, ROLE.USER]);
  }

  /**
    * Returns an object representing the definition of docID in a format appropriate to the restoreOne or define function.
    * @param {String} docID - The ID of the document.
    * @return {Object} - The document's data.
    */

  dumpOne(docID) {
    const doc = this.findDoc(docID);
    return {
      Petty_cash_year6: doc.Petty_cash_year6,
      Petty_cash_year7: doc.Petty_cash_year7,
      Petty_cash_year8: doc.Petty_cash_year8,
      Petty_cash_year9: doc.Petty_cash_year9,
      Cash_year6: doc.Cash_year6,
      Cash_year7: doc.Cash_year7,
      Cash_year8: doc.Cash_year8,
      Cash_year9: doc.Cash_year9,
      Cash_in_banksDraw_on_Line_of_Credit_year6: doc.Cash_in_banksDraw_on_Line_of_Credit_year6,
      Cash_in_banksDraw_on_Line_of_Credit_year7: doc.Cash_in_banksDraw_on_Line_of_Credit_year7,
      Cash_in_banksDraw_on_Line_of_Credit_year8: doc.Cash_in_banksDraw_on_Line_of_Credit_year8,
      Cash_in_banksDraw_on_Line_of_Credit_year9: doc.Cash_in_banksDraw_on_Line_of_Credit_year9,
      Total_Cash_and_Cash_Equivalents_year6: doc.Total_Cash_and_Cash_Equivalents_year6,
      Total_Cash_and_Cash_Equivalents_year7: doc.Total_Cash_and_Cash_Equivalents_year7,
      Total_Cash_and_Cash_Equivalents_year8: doc.Total_Cash_and_Cash_Equivalents_year8,
      Total_Cash_and_Cash_Equivalents_year9: doc.Total_Cash_and_Cash_Equivalents_year9,
      Accounts_receivable_year6: doc.Accounts_receivable_year6,
      Accounts_receivable_year7: doc.Accounts_receivable_year7,
      Accounts_receivable_year8: doc.Accounts_receivable_year8,
      Accounts_receivable_year9: doc.Accounts_receivable_year9,
      Due_from_other_fund_year6: doc.Due_from_other_fund_year6,
      Due_from_other_fund_year7: doc.Due_from_other_fund_year7,
      Due_from_other_fund_year8: doc.Due_from_other_fund_year8,
      Due_from_other_fund_year9: doc.Due_from_other_fund_year9,
      Interest_and_dividends_receivable_year6: doc.Interest_and_dividends_receivable_year6,
      Interest_and_dividends_receivable_year7: doc.Interest_and_dividends_receivable_year7,
      Interest_and_dividends_receivable_year8: doc.Interest_and_dividends_receivable_year8,
      Interest_and_dividends_receivable_year9: doc.Interest_and_dividends_receivable_year9,
      Inventory_prepaid_items_and_other_assets_year6: doc.Inventory_prepaid_items_and_other_assets_year6,
      Inventory_prepaid_items_and_other_assets_year7: doc.Inventory_prepaid_items_and_other_assets_year7,
      Inventory_prepaid_items_and_other_assets_year8: doc.Inventory_prepaid_items_and_other_assets_year8,
      Inventory_prepaid_items_and_other_assets_year9: doc.Inventory_prepaid_items_and_other_assets_year9,
      Notes_receivable_due_within_one_year_year6: doc.Notes_receivable_due_within_one_year_year6,
      Notes_receivable_due_within_one_year_year7: doc.Notes_receivable_due_within_one_year_year7,
      Notes_receivable_due_within_one_year_year8: doc.Notes_receivable_due_within_one_year_year8,
      Notes_receivable_due_within_one_year_year9: doc.Notes_receivable_due_within_one_year_year9,
      Notes_receivable_due_after_one_year_year6: doc.Notes_receivable_due_after_one_year_year6,
      Notes_receivable_due_after_one_year_year7: doc.Notes_receivable_due_after_one_year_year7,
      Notes_receivable_due_after_one_year_year8: doc.Notes_receivable_due_after_one_year_year8,
      Notes_receivable_due_after_one_year_year9: doc.Notes_receivable_due_after_one_year_year9,
      Security_Deposits_year6: doc.Security_Deposits_year6,
      Security_Deposits_year7: doc.Security_Deposits_year7,
      Security_Deposits_year8: doc.Security_Deposits_year8,
      Security_Deposits_year9: doc.Security_Deposits_year9,
      Cash_held_by_investment_manager_year6: doc.Cash_held_by_investment_manager_year6,
      Cash_held_by_investment_manager_year7: doc.Cash_held_by_investment_manager_year7,
      Cash_held_by_investment_manager_year8: doc.Cash_held_by_investment_manager_year8,
      Cash_held_by_investment_manager_year9: doc.Cash_held_by_investment_manager_year9,
      Mutual_Funds_year6: doc.Mutual_Funds_year6,
      Mutual_Funds_year7: doc.Mutual_Funds_year7,
      Mutual_Funds_year8: doc.Mutual_Funds_year8,
      Mutual_Funds_year9: doc.Mutual_Funds_year9,
      Commingled_funds_year6: doc.Commingled_funds_year6,
      Commingled_funds_year7: doc.Commingled_funds_year7,
      Commingled_funds_year8: doc.Commingled_funds_year8,
      Commingled_funds_year9: doc.Commingled_funds_year9,
      Hedge_funds_year6: doc.Hedge_funds_year6,
      Hedge_funds_year7: doc.Hedge_funds_year7,
      Hedge_funds_year8: doc.Hedge_funds_year8,
      Hedge_funds_year9: doc.Hedge_funds_year9,
      Private_equity_year6: doc.Private_equity_year6,
      Private_equity_year7: doc.Private_equity_year7,
      Private_equity_year8: doc.Private_equity_year8,
      Private_equity_year9: doc.Private_equity_year9,
      Common_trust_fund_year6: doc.Common_trust_fund_year6,
      Common_trust_fund_year7: doc.Common_trust_fund_year7,
      Common_trust_fund_year8: doc.Common_trust_fund_year8,
      Common_trust_fund_year9: doc.Common_trust_fund_year9,
      Common_preferred_stock_year6: doc.Common_preferred_stock_year6,
      Common_preferred_stock_year7: doc.Common_preferred_stock_year7,
      Common_preferred_stock_year8: doc.Common_preferred_stock_year8,
      Common_preferred_stock_year9: doc.Common_preferred_stock_year9,
      Private_debt_year6: doc.Private_debt_year6,
      Private_debt_year7: doc.Private_debt_year7,
      Private_debt_year8: doc.Private_debt_year8,
      Private_debt_year9: doc.Private_debt_year9,
      Other_year6: doc.Other_year6,
      Other_year7: doc.Other_year7,
      Other_year8: doc.Other_year8,
      Other_year9: doc.Other_year9,
      Subtotal_Investment_year6: doc.Subtotal_Investment_year6,
      Subtotal_Investment_year7: doc.Subtotal_Investment_year7,
      Subtotal_Investment_year8: doc.Subtotal_Investment_year8,
      Subtotal_Investment_year9: doc.Subtotal_Investment_year9,
      US_treasuries_year6: doc.US_treasuries_year6,
      US_treasuries_year7: doc.US_treasuries_year7,
      US_treasuries_year8: doc.US_treasuries_year8,
      US_treasuries_year9: doc.US_treasuries_year9,
      US_agencies_year6: doc.US_agencies_year6,
      US_agencies_year7: doc.US_agencies_year7,
      US_agencies_year8: doc.US_agencies_year8,
      US_agencies_year9: doc.US_agencies_year9,
      Subtotal_Loan_Fund_year6: doc.Subtotal_Loan_Fund_year6,
      Subtotal_Loan_Fund_year7: doc.Subtotal_Loan_Fund_year7,
      Subtotal_Loan_Fund_year8: doc.Subtotal_Loan_Fund_year8,
      Subtotal_Loan_Fund_year9: doc.Subtotal_Loan_Fund_year9,
      Investments_year6: doc.Investments_year6,
      Investments_year7: doc.Investments_year7,
      Investments_year8: doc.Investments_year8,
      Investments_year9: doc.Investments_year9,
      Buildings_year6: doc.Buildings_year6,
      Buildings_year7: doc.Buildings_year7,
      Buildings_year8: doc.Buildings_year8,
      Buildings_year9: doc.Buildings_year9,
      Leasehold_improvements_year6: doc.Leasehold_improvements_year6,
      Leasehold_improvements_year7: doc.Leasehold_improvements_year7,
      Leasehold_improvements_year8: doc.Leasehold_improvements_year8,
      Leasehold_improvements_year9: doc.Leasehold_improvements_year9,
      Furniture_fixtures_and_equipment_year6: doc.Furniture_fixtures_and_equipment_year6,
      Furniture_fixtures_and_equipment_year7: doc.Furniture_fixtures_and_equipment_year7,
      Furniture_fixtures_and_equipment_year8: doc.Furniture_fixtures_and_equipment_year8,
      Furniture_fixtures_and_equipment_year9: doc.Furniture_fixtures_and_equipment_year9,
      Less_accumulated_depreciation_year6: doc.Less_accumulated_depreciation_year6,
      Less_accumulated_depreciation_year7: doc.Less_accumulated_depreciation_year7,
      Less_accumulated_depreciation_year8: doc.Less_accumulated_depreciation_year8,
      Less_accumulated_depreciation_year9: doc.Less_accumulated_depreciation_year9,
      Net_year6: doc.Net_year6,
      Net_year7: doc.Net_year7,
      Net_year8: doc.Net_year8,
      Net_year9: doc.Net_year9,
      Land_A_year6: doc.Land_A_year6,
      Land_A_year7: doc.Land_A_year7,
      Land_A_year8: doc.Land_A_year8,
      Land_A_year9: doc.Land_A_year9,
      Land_B_year6: doc.Land_B_year6,
      Land_B_year7: doc.Land_B_year7,
      Land_B_year8: doc.Land_B_year8,
      Land_B_year9: doc.Land_B_year9,
      Construction_in_Progress_year6: doc.Construction_in_Progress_year6,
      Construction_in_Progress_year7: doc.Construction_in_Progress_year7,
      Construction_in_Progress_year8: doc.Construction_in_Progress_year8,
      Construction_in_Progress_year9: doc.Construction_in_Progress_year9,
      Subtotal_Capital_Assets_net_year6: doc.Subtotal_Capital_Assets_net_year6,
      Subtotal_Capital_Assets_net_year7: doc.Subtotal_Capital_Assets_net_year7,
      Subtotal_Capital_Assets_net_year8: doc.Subtotal_Capital_Assets_net_year8,
      Subtotal_Capital_Assets_net_year9: doc.Subtotal_Capital_Assets_net_year9,
      Investments_Buildings_year6: doc.Investments_Buildings_year6,
      Investments_Buildings_year7: doc.Investments_Buildings_year7,
      Investments_Buildings_year8: doc.Investments_Buildings_year8,
      Investments_Buildings_year9: doc.Investments_Buildings_year9,
      Investments_Leasehold_improvements_year6: doc.Investments_Leasehold_improvements_year6,
      Investments_Leasehold_improvements_year7: doc.Investments_Leasehold_improvements_year7,
      Investments_Leasehold_improvements_year8: doc.Investments_Leasehold_improvements_year8,
      Investments_Leasehold_improvements_year9: doc.Investments_Leasehold_improvements_year9,
      Investments_Furniture_year6: doc.Investments_Furniture_year6,
      Investments_Furniture_year7: doc.Investments_Furniture_year7,
      Investments_Furniture_year8: doc.Investments_Furniture_year8,
      Investments_Furniture_year9: doc.Investments_Furniture_year9,
      Investments_fixtures_and_equipment_year6: doc.Investments_fixtures_and_equipment_year6,
      Investments_fixtures_and_equipment_year7: doc.Investments_fixtures_and_equipment_year7,
      Investments_fixtures_and_equipment_year8: doc.Investments_fixtures_and_equipment_year8,
      Investments_fixtures_and_equipment_year9: doc.Investments_fixtures_and_equipment_year9,
      Vehicles_year6: doc.Vehicles_year6,
      Vehicles_year7: doc.Vehicles_year7,
      Vehicles_year8: doc.Vehicles_year8,
      Vehicles_year9: doc.Vehicles_year9,
      Investments_Less_accumulated_depreciation_year6: doc.Investments_Less_accumulated_depreciation_year6,
      Investments_Less_accumulated_depreciation_year7: doc.Investments_Less_accumulated_depreciation_year7,
      Investments_Less_accumulated_depreciation_year8: doc.Investments_Less_accumulated_depreciation_year8,
      Investments_Less_accumulated_depreciation_year9: doc.Investments_Less_accumulated_depreciation_year9,
      Investments_Net_year6: doc.Investments_Net_year6,
      Investments_Net_year7: doc.Investments_Net_year7,
      Investments_Net_year8: doc.Investments_Net_year8,
      Investments_Net_year9: doc.Investments_Net_year9,
      Land_year6: doc.Land_year6,
      Land_year7: doc.Land_year7,
      Land_year8: doc.Land_year8,
      Land_year9: doc.Land_year9,
      Subtotal_Limited_Liability_Company_Bs_assets_net_year6: doc.Subtotal_Limited_Liability_Company_Bs_assets_net_year6,
      Subtotal_Limited_Liability_Company_Bs_assets_net_year7: doc.Subtotal_Limited_Liability_Company_Bs_assets_net_year7,
      Subtotal_Limited_Liability_Company_Bs_assets_net_year8: doc.Subtotal_Limited_Liability_Company_Bs_assets_net_year8,
      Subtotal_Limited_Liability_Company_Bs_assets_net_year9: doc.Subtotal_Limited_Liability_Company_Bs_assets_net_year9,
      Capital_Assets_net_year6: doc.Capital_Assets_net_year6,
      Capital_Assets_net_year7: doc.Capital_Assets_net_year7,
      Capital_Assets_net_year8: doc.Capital_Assets_net_year8,
      Capital_Assets_net_year9: doc.Capital_Assets_net_year9,
      Restricted_cash_year6: doc.Restricted_cash_year6,
      Restricted_cash_year7: doc.Restricted_cash_year7,
      Restricted_cash_year8: doc.Restricted_cash_year8,
      Restricted_cash_year9: doc.Restricted_cash_year9,
      Total_Other_Assets_year6: doc.Total_Other_Assets_year6,
      Total_Other_Assets_year7: doc.Total_Other_Assets_year7,
      Total_Other_Assets_year8: doc.Total_Other_Assets_year8,
      Total_Other_Assets_year9: doc.Total_Other_Assets_year9,
      Deferred_outflows_of_resources_related_to_pensions_year6: doc.Deferred_outflows_of_resources_related_to_pensions_year6,
      Deferred_outflows_of_resources_related_to_pensions_year7: doc.Deferred_outflows_of_resources_related_to_pensions_year7,
      Deferred_outflows_of_resources_related_to_pensions_year8: doc.Deferred_outflows_of_resources_related_to_pensions_year8,
      Deferred_outflows_of_resources_related_to_pensions_year9: doc.Deferred_outflows_of_resources_related_to_pensions_year9,
      Deferred_outflows_of_resources_related_to_OPEB_year6: doc.Deferred_outflows_of_resources_related_to_OPEB_year6,
      Deferred_outflows_of_resources_related_to_OPEB_year7: doc.Deferred_outflows_of_resources_related_to_OPEB_year7,
      Deferred_outflows_of_resources_related_to_OPEB_year8: doc.Deferred_outflows_of_resources_related_to_OPEB_year8,
      Deferred_outflows_of_resources_related_to_OPEB_year9: doc.Deferred_outflows_of_resources_related_to_OPEB_year9,
      Total_assets_and_deferred_outflows_of_resources_year6: doc.Total_assets_and_deferred_outflows_of_resources_year6,
      Total_assets_and_deferred_outflows_of_resources_year7: doc.Total_assets_and_deferred_outflows_of_resources_year7,
      Total_assets_and_deferred_outflows_of_resources_year8: doc.Total_assets_and_deferred_outflows_of_resources_year8,
      Total_assets_and_deferred_outflows_of_resources_year9: doc.Total_assets_and_deferred_outflows_of_resources_year9,
      Accounts_payable_and_accrued_liabilities_year6: doc.Accounts_payable_and_accrued_liabilities_year6,
      Accounts_payable_and_accrued_liabilities_year7: doc.Accounts_payable_and_accrued_liabilities_year7,
      Accounts_payable_and_accrued_liabilities_year8: doc.Accounts_payable_and_accrued_liabilities_year8,
      Accounts_payable_and_accrued_liabilities_year9: doc.Accounts_payable_and_accrued_liabilities_year9,
      Due_to_fund_year6: doc.Due_to_fund_year6,
      Due_to_fund_year7: doc.Due_to_fund_year7,
      Due_to_fund_year8: doc.Due_to_fund_year8,
      Due_to_fund_year9: doc.Due_to_fund_year9,
      Due_to_other_fund_year6: doc.Due_to_other_fund_year6,
      Due_to_other_fund_year7: doc.Due_to_other_fund_year7,
      Due_to_other_fund_year8: doc.Due_to_other_fund_year8,
      Due_to_other_fund_year9: doc.Due_to_other_fund_year9,
      Accrued_vacation_year6: doc.Accrued_vacation_year6,
      Accrued_vacation_year7: doc.Accrued_vacation_year7,
      Accrued_vacation_year8: doc.Accrued_vacation_year8,
      Accrued_vacation_year9: doc.Accrued_vacation_year9,
      Workers_compensation_year6: doc.Workers_compensation_year6,
      Workers_compensation_year7: doc.Workers_compensation_year7,
      Workers_compensation_year8: doc.Workers_compensation_year8,
      Workers_compensation_year9: doc.Workers_compensation_year9,
      Accrued_management_retirement_plan_year6: doc.Accrued_management_retirement_plan_year6,
      Accrued_management_retirement_plan_year7: doc.Accrued_management_retirement_plan_year7,
      Accrued_management_retirement_plan_year8: doc.Accrued_management_retirement_plan_year8,
      Accrued_management_retirement_plan_year9: doc.Accrued_management_retirement_plan_year9,
      Accrued_lease_guaranty_obligation_year6: doc.Accrued_lease_guaranty_obligation_year6,
      Accrued_lease_guaranty_obligation_year7: doc.Accrued_lease_guaranty_obligation_year7,
      Accrued_lease_guaranty_obligation_year8: doc.Accrued_lease_guaranty_obligation_year8,
      Accrued_lease_guaranty_obligation_year9: doc.Accrued_lease_guaranty_obligation_year9,
      Capital_lease_obligation_year6: doc.Capital_lease_obligation_year6,
      Capital_lease_obligation_year7: doc.Capital_lease_obligation_year7,
      Capital_lease_obligation_year8: doc.Capital_lease_obligation_year8,
      Capital_lease_obligation_year9: doc.Capital_lease_obligation_year9,
      Notes_payable_Building_A_acquisition_year6: doc.Notes_payable_Building_A_acquisition_year6,
      Notes_payable_Building_A_acquisition_year7: doc.Notes_payable_Building_A_acquisition_year7,
      Notes_payable_Building_A_acquisition_year8: doc.Notes_payable_Building_A_acquisition_year8,
      Notes_payable_Building_A_acquisition_year9: doc.Notes_payable_Building_A_acquisition_year9,
      Net_Pension_Liability_year6: doc.Net_Pension_Liability_year6,
      Net_Pension_Liability_year7: doc.Net_Pension_Liability_year7,
      Net_Pension_Liability_year8: doc.Net_Pension_Liability_year8,
      Net_Pension_Liability_year9: doc.Net_Pension_Liability_year9,
      Net_OPEB_Liability_year6: doc.Net_OPEB_Liability_year6,
      Net_OPEB_Liability_year7: doc.Net_OPEB_Liability_year7,
      Net_OPEB_Liability_year8: doc.Net_OPEB_Liability_year8,
      Net_OPEB_Liability_year9: doc.Net_OPEB_Liability_year9,
      Line_of_Credit_Building_A_year6: doc.Line_of_Credit_Building_A_year6,
      Line_of_Credit_Building_A_year7: doc.Line_of_Credit_Building_A_year7,
      Line_of_Credit_Building_A_year8: doc.Line_of_Credit_Building_A_year8,
      Line_of_Credit_Building_A_year9: doc.Line_of_Credit_Building_A_year9,
      Line_of_Credit_Building_B_year6: doc.Line_of_Credit_Building_B_year6,
      Line_of_Credit_Building_B_year7: doc.Line_of_Credit_Building_B_year7,
      Line_of_Credit_Building_B_year8: doc.Line_of_Credit_Building_B_year8,
      Line_of_Credit_Building_B_year9: doc.Line_of_Credit_Building_B_year9,
      Debt_service_year6: doc.Debt_service_year6,
      Debt_service_year7: doc.Debt_service_year7,
      Debt_service_year8: doc.Debt_service_year8,
      Debt_service_year9: doc.Debt_service_year9,
      Longterm_liabilities_due_within_one_year_year6: doc.Longterm_liabilities_due_within_one_year_year6,
      Longterm_liabilities_due_within_one_year_year7: doc.Longterm_liabilities_due_within_one_year_year7,
      Longterm_liabilities_due_within_one_year_year8: doc.Longterm_liabilities_due_within_one_year_year8,
      Longterm_liabilities_due_within_one_year_year9: doc.Longterm_liabilities_due_within_one_year_year9,
      Long_term_Accrued_vacation_year6: doc.Long_term_Accrued_vacation_year6,
      Long_term_Accrued_vacation_year7: doc.Long_term_Accrued_vacation_year7,
      Long_term_Accrued_vacation_year8: doc.Long_term_Accrued_vacation_year8,
      Long_term_Accrued_vacation_year9: doc.Long_term_Accrued_vacation_year9,
      Long_term_Workers_compensation_year6: doc.Long_term_Workers_compensation_year6,
      Long_term_Workers_compensation_year7: doc.Long_term_Workers_compensation_year7,
      Long_term_Workers_compensation_year8: doc.Long_term_Workers_compensation_year8,
      Long_term_Workers_compensation_year9: doc.Long_term_Workers_compensation_year9,
      Long_term_Accrued_management_retirement_plan_year6: doc.Long_term_Accrued_management_retirement_plan_year6,
      Long_term_Accrued_management_retirement_plan_year7: doc.Long_term_Accrued_management_retirement_plan_year7,
      Long_term_Accrued_management_retirement_plan_year8: doc.Long_term_Accrued_management_retirement_plan_year8,
      Long_term_Accrued_management_retirement_plan_year9: doc.Long_term_Accrued_management_retirement_plan_year9,
      Long_term_Accrued_lease_guaranty_obligation_year6: doc.Long_term_Accrued_lease_guaranty_obligation_year6,
      Long_term_Accrued_lease_guaranty_obligation_year7: doc.Long_term_Accrued_lease_guaranty_obligation_year7,
      Long_term_Accrued_lease_guaranty_obligation_year8: doc.Long_term_Accrued_lease_guaranty_obligation_year8,
      Long_term_Accrued_lease_guaranty_obligation_year9: doc.Long_term_Accrued_lease_guaranty_obligation_year9,
      Long_term_Capital_lease_obligation_year6: doc.Long_term_Capital_lease_obligation_year6,
      Long_term_Capital_lease_obligation_year7: doc.Long_term_Capital_lease_obligation_year7,
      Long_term_Capital_lease_obligation_year8: doc.Long_term_Capital_lease_obligation_year8,
      Long_term_Capital_lease_obligation_year9: doc.Long_term_Capital_lease_obligation_year9,
      Long_term_Notes_payable_Building_A_acquisition_year6: doc.Long_term_Notes_payable_Building_A_acquisition_year6,
      Long_term_Notes_payable_Building_A_acquisition_year7: doc.Long_term_Notes_payable_Building_A_acquisition_year7,
      Long_term_Notes_payable_Building_A_acquisition_year8: doc.Long_term_Notes_payable_Building_A_acquisition_year8,
      Long_term_Notes_payable_Building_A_acquisition_year9: doc.Long_term_Notes_payable_Building_A_acquisition_year9,
      Long_term_Net_Pension_Liability_year6: doc.Long_term_Net_Pension_Liability_year6,
      Long_term_Net_Pension_Liability_year7: doc.Long_term_Net_Pension_Liability_year7,
      Long_term_Net_Pension_Liability_year8: doc.Long_term_Net_Pension_Liability_year8,
      Long_term_Net_Pension_Liability_year9: doc.Long_term_Net_Pension_Liability_year9,
      Long_term_Net_OPEB_Liability_year6: doc.Long_term_Net_OPEB_Liability_year6,
      Long_term_Net_OPEB_Liability_year7: doc.Long_term_Net_OPEB_Liability_year7,
      Long_term_Net_OPEB_Liability_year8: doc.Long_term_Net_OPEB_Liability_year8,
      Long_term_Net_OPEB_Liability_year9: doc.Long_term_Net_OPEB_Liability_year9,
      Long_term_Line_of_Credit_Building_A_year6: doc.Long_term_Line_of_Credit_Building_A_year6,
      Long_term_Line_of_Credit_Building_A_year7: doc.Long_term_Line_of_Credit_Building_A_year7,
      Long_term_Line_of_Credit_Building_A_year8: doc.Long_term_Line_of_Credit_Building_A_year8,
      Long_term_Line_of_Credit_Building_A_year9: doc.Long_term_Line_of_Credit_Building_A_year9,
      Long_term_Line_of_Credit_Building_B_year6: doc.Long_term_Line_of_Credit_Building_B_year6,
      Long_term_Line_of_Credit_Building_B_year7: doc.Long_term_Line_of_Credit_Building_B_year7,
      Long_term_Line_of_Credit_Building_B_year8: doc.Long_term_Line_of_Credit_Building_B_year8,
      Long_term_Line_of_Credit_Building_B_year9: doc.Long_term_Line_of_Credit_Building_B_year9,
      Long_term_Debt_service_year6: doc.Long_term_Debt_service_year6,
      Long_term_Debt_service_year7: doc.Long_term_Debt_service_year7,
      Long_term_Debt_service_year8: doc.Long_term_Debt_service_year8,
      Long_term_Debt_service_year9: doc.Long_term_Debt_service_year9,
      Longterm_liabilities_due_after_one_year_year6: doc.Longterm_liabilities_due_after_one_year_year6,
      Longterm_liabilities_due_after_one_year_year7: doc.Longterm_liabilities_due_after_one_year_year7,
      Longterm_liabilities_due_after_one_year_year8: doc.Longterm_liabilities_due_after_one_year_year8,
      Longterm_liabilities_due_after_one_year_year9: doc.Longterm_liabilities_due_after_one_year_year9,
      Total_Liabilities_year6: doc.Total_Liabilities_year6,
      Total_Liabilities_year7: doc.Total_Liabilities_year7,
      Total_Liabilities_year8: doc.Total_Liabilities_year8,
      Total_Liabilities_year9: doc.Total_Liabilities_year9,
      Deferred_inflows_of_resources_related_to_pensions_year6: doc.Deferred_inflows_of_resources_related_to_pensions_year6,
      Deferred_inflows_of_resources_related_to_pensions_year7: doc.Deferred_inflows_of_resources_related_to_pensions_year7,
      Deferred_inflows_of_resources_related_to_pensions_year8: doc.Deferred_inflows_of_resources_related_to_pensions_year8,
      Deferred_inflows_of_resources_related_to_pensions_year9: doc.Deferred_inflows_of_resources_related_to_pensions_year9,
      Deferred_inflows_of_resources_related_to_OPEB_year6: doc.Deferred_inflows_of_resources_related_to_OPEB_year6,
      Deferred_inflows_of_resources_related_to_OPEB_year7: doc.Deferred_inflows_of_resources_related_to_OPEB_year7,
      Deferred_inflows_of_resources_related_to_OPEB_year8: doc.Deferred_inflows_of_resources_related_to_OPEB_year8,
      Deferred_inflows_of_resources_related_to_OPEB_year9: doc.Deferred_inflows_of_resources_related_to_OPEB_year9,
      Total_liabilities_and_deferred_inflows_of_resources_year6: doc.Total_liabilities_and_deferred_inflows_of_resources_year6,
      Total_liabilities_and_deferred_inflows_of_resources_year7: doc.Total_liabilities_and_deferred_inflows_of_resources_year7,
      Total_liabilities_and_deferred_inflows_of_resources_year8: doc.Total_liabilities_and_deferred_inflows_of_resources_year8,
      Total_liabilities_and_deferred_inflows_of_resources_year9: doc.Total_liabilities_and_deferred_inflows_of_resources_year9,
      Invested_in_capital_assets_net_of_related_debt_year6: doc.Invested_in_capital_assets_net_of_related_debt_year6,
      Invested_in_capital_assets_net_of_related_debt_year7: doc.Invested_in_capital_assets_net_of_related_debt_year7,
      Invested_in_capital_assets_net_of_related_debt_year8: doc.Invested_in_capital_assets_net_of_related_debt_year8,
      Invested_in_capital_assets_net_of_related_debt_year9: doc.Invested_in_capital_assets_net_of_related_debt_year9,
      Restricted_federal_funds_year6: doc.Restricted_federal_funds_year6,
      Restricted_federal_funds_year7: doc.Restricted_federal_funds_year7,
      Restricted_federal_funds_year8: doc.Restricted_federal_funds_year8,
      Restricted_federal_funds_year9: doc.Restricted_federal_funds_year9,
      Unrestricted_year6: doc.Unrestricted_year6,
      Unrestricted_year7: doc.Unrestricted_year7,
      Unrestricted_year8: doc.Unrestricted_year8,
      Unrestricted_year9: doc.Unrestricted_year9,
      Total_net_position_year6: doc.Total_net_position_year6,
      Total_net_position_year7: doc.Total_net_position_year7,
      Total_net_position_year8: doc.Total_net_position_year8,
      Total_net_position_year9: doc.Total_net_position_year9,
      Total_Liabilities_Deferred_Inflows_of_Resources_and_Net_Position_year6: doc.Total_Liabilities_Deferred_Inflows_of_Resources_and_Net_Position_year6,
      Total_Liabilities_Deferred_Inflows_of_Resources_and_Net_Position_year7: doc.Total_Liabilities_Deferred_Inflows_of_Resources_and_Net_Position_year7,
      Total_Liabilities_Deferred_Inflows_of_Resources_and_Net_Position_year8: doc.Total_Liabilities_Deferred_Inflows_of_Resources_and_Net_Position_year8,
      Total_Liabilities_Deferred_Inflows_of_Resources_and_Net_Position_year9: doc.Total_Liabilities_Deferred_Inflows_of_Resources_and_Net_Position_year9,
    };
  }
}
export const AuditedBalanceSheets = new AuditedBalanceSheetCollection();
if (Meteor.isServer) {
  AuditedBalanceSheets._collection.allow({
    insert(userId, doc) {
      return !!userId; // Only logged-in users can insert
    },
    update(userId, doc, fields, modifier) {
      return doc.owner === Meteor.users.findOne(userId).username; // Only owners can update
    },
    remove(userId, doc) {
      return doc.owner === Meteor.users.findOne(userId).username; // Only owners can remove
    },
  });
}
