import { Meteor } from 'meteor/meteor';
import { ROLE } from '../../api/role/Role';
import { AdminProfiles } from '../../api/user/AdminProfileCollection';
import { UserProfiles } from '../../api/user/UserProfileCollection';
import { AuditedBalanceSheets } from '../../api/Inputs/auditedBalanceSheet.js';

/* eslint-disable no-console */

// Function to create a new AuditedBalanceSheet with all fields set to zero
function createAuditedBalanceSheet(userId) {
  console.log(`Creating audited balance sheet for user ${userId}`);
  const auditedBalanceSheetData = {
    owner: userId,
    Petty_cash_year6: 0,
    Petty_cash_year7: 0,
    Petty_cash_year8: 0,
    Petty_cash_year9: 0,
    Cash_year6: 0,
    Cash_year7: 0,
    Cash_year8: 0,
    Cash_year9: 0,
    Cash_in_banksDraw_on_Line_of_Credit_year6: 0,
    Cash_in_banksDraw_on_Line_of_Credit_year7: 0,
    Cash_in_banksDraw_on_Line_of_Credit_year8: 0,
    Cash_in_banksDraw_on_Line_of_Credit_year9: 0,
    Total_Cash_and_Cash_Equivalents_year6: 0,
    Total_Cash_and_Cash_Equivalents_year7: 0,
    Total_Cash_and_Cash_Equivalents_year8: 0,
    Total_Cash_and_Cash_Equivalents_year9: 0,
    Accounts_receivable_year6: 0,
    Accounts_receivable_year7: 0,
    Accounts_receivable_year8: 0,
    Accounts_receivable_year9: 0,
    Due_from_other_fund_year6: 0,
    Due_from_other_fund_year7: 0,
    Due_from_other_fund_year8: 0,
    Due_from_other_fund_year9: 0,
    Interest_and_dividends_receivable_year6: 0,
    Interest_and_dividends_receivable_year7: 0,
    Interest_and_dividends_receivable_year8: 0,
    Interest_and_dividends_receivable_year9: 0,
    Inventory_prepaid_items_and_other_assets_year6: 0,
    Inventory_prepaid_items_and_other_assets_year7: 0,
    Inventory_prepaid_items_and_other_assets_year8: 0,
    Inventory_prepaid_items_and_other_assets_year9: 0,
    Notes_receivable_due_within_one_year_year6: 0,
    Notes_receivable_due_within_one_year_year7: 0,
    Notes_receivable_due_within_one_year_year8: 0,
    Notes_receivable_due_within_one_year_year9: 0,
    Notes_receivable_due_after_one_year_year6: 0,
    Notes_receivable_due_after_one_year_year7: 0,
    Notes_receivable_due_after_one_year_year8: 0,
    Notes_receivable_due_after_one_year_year9: 0,
    Security_Deposits_year6: 0,
    Security_Deposits_year7: 0,
    Security_Deposits_year8: 0,
    Security_Deposits_year9: 0,
    Cash_held_by_investment_manager_year6: 0,
    Cash_held_by_investment_manager_year7: 0,
    Cash_held_by_investment_manager_year8: 0,
    Cash_held_by_investment_manager_year9: 0,
    Mutual_Funds_year6: 0,
    Mutual_Funds_year7: 0,
    Mutual_Funds_year8: 0,
    Mutual_Funds_year9: 0,
    Commingled_funds_year6: 0,
    Commingled_funds_year7: 0,
    Commingled_funds_year8: 0,
    Commingled_funds_year9: 0,
    Hedge_funds_year6: 0,
    Hedge_funds_year7: 0,
    Hedge_funds_year8: 0,
    Hedge_funds_year9: 0,
    Private_equity_year6: 0,
    Private_equity_year7: 0,
    Private_equity_year8: 0,
    Private_equity_year9: 0,
    Common_trust_fund_year6: 0,
    Common_trust_fund_year7: 0,
    Common_trust_fund_year8: 0,
    Common_trust_fund_year9: 0,
    Common_preferred_stock_year6: 0,
    Common_preferred_stock_year7: 0,
    Common_preferred_stock_year8: 0,
    Common_preferred_stock_year9: 0,
    Private_debt_year6: 0,
    Private_debt_year7: 0,
    Private_debt_year8: 0,
    Private_debt_year9: 0,
    Other_year6: 0,
    Other_year7: 0,
    Other_year8: 0,
    Other_year9: 0,
    Subtotal_Investment_year6: 0,
    Subtotal_Investment_year7: 0,
    Subtotal_Investment_year8: 0,
    Subtotal_Investment_year9: 0,
    US_treasuries_year6: 0,
    US_treasuries_year7: 0,
    US_treasuries_year8: 0,
    US_treasuries_year9: 0,
    US_agencies_year6: 0,
    US_agencies_year7: 0,
    US_agencies_year8: 0,
    US_agencies_year9: 0,
    Subtotal_Loan_Fund_year6: 0,
    Subtotal_Loan_Fund_year7: 0,
    Subtotal_Loan_Fund_year8: 0,
    Subtotal_Loan_Fund_year9: 0,
    Investments_year6: 0,
    Investments_year7: 0,
    Investments_year8: 0,
    Investments_year9: 0,
    Buildings_year6: 0,
    Buildings_year7: 0,
    Buildings_year8: 0,
    Buildings_year9: 0,
    Leasehold_improvements_year6: 0,
    Leasehold_improvements_year7: 0,
    Leasehold_improvements_year8: 0,
    Leasehold_improvements_year9: 0,
    Furniture_fixtures_and_equipment_year6: 0,
    Furniture_fixtures_and_equipment_year7: 0,
    Furniture_fixtures_and_equipment_year8: 0,
    Furniture_fixtures_and_equipment_year9: 0,
    Less_accumulated_depreciation_year6: 0,
    Less_accumulated_depreciation_year7: 0,
    Less_accumulated_depreciation_year8: 0,
    Less_accumulated_depreciation_year9: 0,
    Net_year6: 0,
    Net_year7: 0,
    Net_year8: 0,
    Net_year9: 0,
    Land_A_year6: 0,
    Land_A_year7: 0,
    Land_A_year8: 0,
    Land_A_year9: 0,
    Land_B_year6: 0,
    Land_B_year7: 0,
    Land_B_year8: 0,
    Land_B_year9: 0,
    Construction_in_Progress_year6: 0,
    Construction_in_Progress_year7: 0,
    Construction_in_Progress_year8: 0,
    Construction_in_Progress_year9: 0,
    Subtotal_Capital_Assets_net_year6: 0,
    Subtotal_Capital_Assets_net_year7: 0,
    Subtotal_Capital_Assets_net_year8: 0,
    Subtotal_Capital_Assets_net_year9: 0,
    Capital_Assets_net_year6: 0,
    Capital_Assets_net_year7: 0,
    Capital_Assets_net_year8: 0,
    Capital_Assets_net_year9: 0,
    Restricted_cash_year6: 0,
    Restricted_cash_year7: 0,
    Restricted_cash_year8: 0,
    Restricted_cash_year9: 0,
    Total_Other_Assets_year6: 0,
    Total_Other_Assets_year7: 0,
    Total_Other_Assets_year8: 0,
    Total_Other_Assets_year9: 0,
    Deferred_outflows_of_resources_related_to_pensions_year6: 0,
    Deferred_outflows_of_resources_related_to_pensions_year7: 0,
    Deferred_outflows_of_resources_related_to_pensions_year8: 0,
    Deferred_outflows_of_resources_related_to_pensions_year9: 0,
    Deferred_outflows_of_resources_related_to_OPEB_year6: 0,
    Deferred_outflows_of_resources_related_to_OPEB_year7: 0,
    Deferred_outflows_of_resources_related_to_OPEB_year8: 0,
    Deferred_outflows_of_resources_related_to_OPEB_year9: 0,
    Total_assets_and_deferred_outflows_of_resources_year6: 0,
    Total_assets_and_deferred_outflows_of_resources_year7: 0,
    Total_assets_and_deferred_outflows_of_resources_year8: 0,
    Total_assets_and_deferred_outflows_of_resources_year9: 0,
    Accounts_payable_and_accrued_liabilities_year6: 0,
    Accounts_payable_and_accrued_liabilities_year7: 0,
    Accounts_payable_and_accrued_liabilities_year8: 0,
    Accounts_payable_and_accrued_liabilities_year9: 0,
    Due_to_fund_year6: 0,
    Due_to_fund_year7: 0,
    Due_to_fund_year8: 0,
    Due_to_fund_year9: 0,
    Due_to_other_fund_year6: 0,
    Due_to_other_fund_year7: 0,
    Due_to_other_fund_year8: 0,
    Due_to_other_fund_year9: 0,
    Accrued_vacation_year6: 0,
    Accrued_vacation_year7: 0,
    Accrued_vacation_year8: 0,
    Accrued_vacation_year9: 0,
    Workers_compensation_year6: 0,
    Workers_compensation_year7: 0,
    Workers_compensation_year8: 0,
    Workers_compensation_year9: 0,
    Accrued_management_retirement_plan_year6: 0,
    Accrued_management_retirement_plan_year7: 0,
    Accrued_management_retirement_plan_year8: 0,
    Accrued_management_retirement_plan_year9: 0,
    Accrued_lease_guaranty_obligation_year6: 0,
    Accrued_lease_guaranty_obligation_year7: 0,
    Accrued_lease_guaranty_obligation_year8: 0,
    Accrued_lease_guaranty_obligation_year9: 0,
    Capital_lease_obligation_year6: 0,
    Capital_lease_obligation_year7: 0,
    Capital_lease_obligation_year8: 0,
    Capital_lease_obligation_year9: 0,
    Notes_payable_Building_A_acquisition_year6: 0,
    Notes_payable_Building_A_acquisition_year7: 0,
    Notes_payable_Building_A_acquisition_year8: 0,
    Notes_payable_Building_A_acquisition_year9: 0,
    Net_Pension_Liability_year6: 0,
    Net_Pension_Liability_year7: 0,
    Net_Pension_Liability_year8: 0,
    Net_Pension_Liability_year9: 0,
    Net_OPEB_Liability_year6: 0,
    Net_OPEB_Liability_year7: 0,
    Net_OPEB_Liability_year8: 0,
    Net_OPEB_Liability_year9: 0,
    Line_of_Credit_Building_A_year6: 0,
    Line_of_Credit_Building_A_year7: 0,
    Line_of_Credit_Building_A_year8: 0,
    Line_of_Credit_Building_A_year9: 0,
    Line_of_Credit_Building_B_year6: 0,
    Line_of_Credit_Building_B_year7: 0,
    Line_of_Credit_Building_B_year8: 0,
    Line_of_Credit_Building_B_year9: 0,
    Debt_service_year6: 0,
    Debt_service_year7: 0,
    Debt_service_year8: 0,
    Debt_service_year9: 0,
    Longterm_liabilities_due_within_one_year_year6: 0,
    Longterm_liabilities_due_within_one_year_year7: 0,
    Longterm_liabilities_due_within_one_year_year8: 0,
    Longterm_liabilities_due_within_one_year_year9: 0,
    Long_term_Accrued_vacation_year6: 0,
    Long_term_Accrued_vacation_year7: 0,
    Long_term_Accrued_vacation_year8: 0,
    Long_term_Accrued_vacation_year9: 0,
    Long_term_Workers_compensation_year6: 0,
    Long_term_Workers_compensation_year7: 0,
    Long_term_Workers_compensation_year8: 0,
    Long_term_Workers_compensation_year9: 0,
    Long_term_Accrued_management_retirement_plan_year6: 0,
    Long_term_Accrued_management_retirement_plan_year7: 0,
    Long_term_Accrued_management_retirement_plan_year8: 0,
    Long_term_Accrued_management_retirement_plan_year9: 0,
    Long_term_Accrued_lease_guaranty_obligation_year6: 0,
    Long_term_Accrued_lease_guaranty_obligation_year7: 0,
    Long_term_Accrued_lease_guaranty_obligation_year8: 0,
    Long_term_Accrued_lease_guaranty_obligation_year9: 0,
    Long_term_Capital_lease_obligation_year6: 0,
    Long_term_Capital_lease_obligation_year7: 0,
    Long_term_Capital_lease_obligation_year8: 0,
    Long_term_Capital_lease_obligation_year9: 0,
    Long_term_Notes_payable_Building_A_acquisition_year6: 0,
    Long_term_Notes_payable_Building_A_acquisition_year7: 0,
    Long_term_Notes_payable_Building_A_acquisition_year8: 0,
    Long_term_Notes_payable_Building_A_acquisition_year9: 0,
    Long_term_Net_Pension_Liability_year6: 0,
    Long_term_Net_Pension_Liability_year7: 0,
    Long_term_Net_Pension_Liability_year8: 0,
    Long_term_Net_Pension_Liability_year9: 0,
    Long_term_Net_OPEB_Liability_year6: 0,
    Long_term_Net_OPEB_Liability_year7: 0,
    Long_term_Net_OPEB_Liability_year8: 0,
    Long_term_Net_OPEB_Liability_year9: 0,
    Long_term_Line_of_Credit_Building_A_year6: 0,
    Long_term_Line_of_Credit_Building_A_year7: 0,
    Long_term_Line_of_Credit_Building_A_year8: 0,
    Long_term_Line_of_Credit_Building_A_year9: 0,
    Long_term_Line_of_Credit_Building_B_year6: 0,
    Long_term_Line_of_Credit_Building_B_year7: 0,
    Long_term_Line_of_Credit_Building_B_year8: 0,
    Long_term_Line_of_Credit_Building_B_year9: 0,
    Long_term_Debt_service_year6: 0,
    Long_term_Debt_service_year7: 0,
    Long_term_Debt_service_year8: 0,
    Long_term_Debt_service_year9: 0,
    Longterm_liabilities_due_after_one_year_year6: 0,
    Longterm_liabilities_due_after_one_year_year7: 0,
    Longterm_liabilities_due_after_one_year_year8: 0,
    Longterm_liabilities_due_after_one_year_year9: 0,
    Total_Liabilities_year6: 0,
    Total_Liabilities_year7: 0,
    Total_Liabilities_year8: 0,
    Total_Liabilities_year9: 0,
    Deferred_inflows_of_resources_related_to_pensions_year6: 0,
    Deferred_inflows_of_resources_related_to_pensions_year7: 0,
    Deferred_inflows_of_resources_related_to_pensions_year8: 0,
    Deferred_inflows_of_resources_related_to_pensions_year9: 0,
    Deferred_inflows_of_resources_related_to_OPEB_year6: 0,
    Deferred_inflows_of_resources_related_to_OPEB_year7: 0,
    Deferred_inflows_of_resources_related_to_OPEB_year8: 0,
    Deferred_inflows_of_resources_related_to_OPEB_year9: 0,
    Total_liabilities_and_deferred_inflows_of_resources_year6: 0,
    Total_liabilities_and_deferred_inflows_of_resources_year7: 0,
    Total_liabilities_and_deferred_inflows_of_resources_year8: 0,
    Total_liabilities_and_deferred_inflows_of_resources_year9: 0,
    Invested_in_capital_assets_net_of_related_debt_year6: 0,
    Invested_in_capital_assets_net_of_related_debt_year7: 0,
    Invested_in_capital_assets_net_of_related_debt_year8: 0,
    Invested_in_capital_assets_net_of_related_debt_year9: 0,
    Restricted_federal_funds_year6: 0,
    Restricted_federal_funds_year7: 0,
    Restricted_federal_funds_year8: 0,
    Restricted_federal_funds_year9: 0,
    Unrestricted_year6: 0,
    Unrestricted_year7: 0,
    Unrestricted_year8: 0,
    Unrestricted_year9: 0,
    Total_net_position_year6: 0,
    Total_net_position_year7: 0,
    Total_net_position_year8: 0,
    Total_net_position_year9: 0,
    Total_Liabilities_Deferred_Inflows_of_Resources_and_Net_Position_year6: 0,
    Total_Liabilities_Deferred_Inflows_of_Resources_and_Net_Position_year7: 0,
    Total_Liabilities_Deferred_Inflows_of_Resources_and_Net_Position_year8: 0,
    Total_Liabilities_Deferred_Inflows_of_Resources_and_Net_Position_year9: 0,
  };

  try {
    const docID = AuditedBalanceSheets.define(auditedBalanceSheetData);
    console.log(`Audited balance sheet created with docID: ${docID}`);
  } catch (error) {
    console.error('Error creating audited balance sheet:', error);
  }
}

// Function to create a new user and then their balance sheet
function createUser(email, role, firstName, lastName, password) {
  console.log(`  Creating user ${email} with role ${role}.`);

  // User creation process
  if (role === ROLE.ADMIN) {
    AdminProfiles.define({ email, firstName, lastName, password });
  } else { // everyone else is just a user.
    UserProfiles.define({ email, firstName, lastName, password });
  }

  // Make sure the user is created before creating the audited balance sheet
  Meteor.setTimeout(() => {
    const user = Meteor.users.findOne({ 'emails.address': email });
    if (user) {
      createAuditedBalanceSheet(user._id);
    } else {
      console.error(`Error: Unable to find user with email ${email} to create balance sheet.`);
    }
  }, 10000); // Small delay to allow user creation before trying to find the userId
}

// When running app for the first time, pass a settings file to set up a default user account.
if (Meteor.users.find().count() === 0) {
  if (Meteor.settings.defaultAccounts) {
    console.log('Creating the default user(s)');
    Meteor.settings.defaultAccounts.forEach(({ email, password, role, firstName, lastName }) => createUser(email, role, firstName, lastName, password));
  } else {
    console.log('Cannot initialize the database! Please invoke meteor with a settings file.');
  }
}
