/** Define ids for each page. */
export const PAGE_IDS = {
  ADD_STUFF: 'add-stuff',
  DASHBOARD: 'dashboard',
  AUDITED_BALANCE_INPUT: 'audited-balance-input',
  BUDGET_PL_INPUT: 'budget-pl-input',
  AUDITED_INPUT: 'audited-input',
  DATA_INPUT: 'data-input',
  LIST_DATA: 'list-data',
  EDIT_STUFF: 'edit-stuff',
  LANDING: 'landing',
  LIST_STUFF: 'list-stuff',
  LIST_STUFF_ADMIN: 'list-stuff-admin',
  MANAGE_DATABASE: 'manage-database',
  NOT_AUTHORIZED: 'not-authorized',
  NOT_FOUND: 'not-found',
  SIGN_IN: 'sign-in',
  SIGN_OUT: 'sign-out',
  SIGN_UP: 'sign-up',
};
