export const TOOLTIP_TEXTS = {
  PETTY_CASH: 'Refers to a small amount of cash set aside for small fees.',
  CASH: 'Refers to any regular cash for any fees.',
  CASH_IN_BANKS: 'Refers to a financial loan that allows a business to borrow up to a certain amount of money.',
  ACCOUNTS_RECEIVE: 'Outstanding payment owed to a business.',
  DUE_FUNDS: 'Refers to an asset account that keeps track of funds owed to another company at another firm.',
  INTEREST: 'Interests receivable is interest that has yet to be collected, and dividends receivable are dividends that a company claims but have yet to be paid to the shareholders. These are both assets.',
  PREPAID: 'These are administrative expenses like legal retainers, leases, and other ongoing expenses that are paid in advance.',
  NOTES_RECEIVE: 'These are written promises by the debtor that record the amount they need to pay the creditor.',
  NOTES_RECEIVE_AFTER: 'Notes receivable expected to be paid after a year or longer (non-current asset).',
  SECURITY: 'Sum paid to a tenant to cover any potential loss or damage.',
  CASH_HELD: 'On-hand liquid assets held by an investment manager for short-term obligations and liquidity needs.',
  MUTUAL_FUNDS: 'Investment vehicle where funds from multiple shareholders that trades in a variety of holdings. This program is managed by professionals.',
  COMMINGLED_FUNDS: 'A fund accumulated from different investors into one fund courtesy of an investment manager.',
  HEDGE_FUNDS: 'A limited partnership where money from multiple investors using risky methods is pooled and managed by fund managers to make capital gains.',
  PRIVATE_EQUITY: 'Refers to investments made into private companies not listed on public stock exchanges.',
  ACCOUNTS_PAYABLE: 'Accruals are expenses that have not been received or paid yet. Accounts payable is a type of accrual where a company receives goods prior to paying for it.',
  DUE_TO_FUND: 'This is the amount of funds due to another company. They can be short term or long term funds. This is generally counted as liability on the balance sheet.',
  DUE_TO_OTHER_FUND: 'This is the amount of funds owed to another fund.',
};
